// src/components/SettingsWidget.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { Moon, Sun } from "lucide-svelte";
	import Button from "@/components/ui/Button.svelte";
	import { themeState, toggleTheme } from "@/lib/theme.svelte";
	import { textSizeState, setTextSize, type TextSize } from "@/lib/text-size.svelte";

	let mounted = $state(false);
	onMount(() => {
		mounted = true;
	});

	function pickSize(s: TextSize) {
		setTextSize(s);
	}
</script>

{#if mounted}
	<div
		role="toolbar"
		aria-label="Display settings"
		class="flex items-center gap-1 border border-border/40 rounded-none p-1 bg-background/85"
	>
		<Button
			variant={textSizeState.size === "small" ? "secondary" : "ghost"}
			size="icon"
			type="button"
			class="min-h-11 min-w-11 h-11 w-11"
			aria-label="Small text size"
			aria-pressed={textSizeState.size === "small"}
			onclick={() => pickSize("small")}
		>
			<span class="text-xs font-bold">A</span>
		</Button>
		<Button
			variant={textSizeState.size === "normal" ? "secondary" : "ghost"}
			size="icon"
			type="button"
			class="min-h-11 min-w-11 h-11 w-11"
			aria-label="Normal text size"
			aria-pressed={textSizeState.size === "normal"}
			onclick={() => pickSize("normal")}
		>
			<span class="text-sm font-bold">A</span>
		</Button>
		<Button
			variant={textSizeState.size === "large" ? "secondary" : "ghost"}
			size="icon"
			type="button"
			class="min-h-11 min-w-11 h-11 w-11"
			aria-label="Large text size"
			aria-pressed={textSizeState.size === "large"}
			onclick={() => pickSize("large")}
		>
			<span class="text-lg font-bold">A</span>
		</Button>

		<div class="w-px h-4 bg-border/50 mx-1" aria-hidden="true"></div>

		<Button
			variant="ghost"
			size="icon"
			type="button"
			class="min-h-11 min-w-11 h-11 w-11"
			aria-label={themeState.mode === "dark" ? "Switch to light theme" : "Switch to dark theme"}
			onclick={toggleTheme}
		>
			{#if themeState.mode === "dark"}
				<Sun class="size-4" aria-hidden="true" />
			{:else}
				<Moon class="size-4" aria-hidden="true" />
			{/if}
		</Button>
	</div>
{/if}

// components/settings-widget.tsx
"use client";

import { Moon, Sun } from "lucide-react";
import { useTheme } from "next-themes";
import { Button } from "@/components/ui/button";
import { useTextSize } from "@/components/text-size-provider";
import { useEffect, useState } from "react";

export function SettingsWidget() {
    const { theme, setTheme, resolvedTheme } = useTheme();
    const { size, setSize } = useTextSize();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) return null;

    const toggleTheme = () => {
        setTheme(resolvedTheme === "dark" ? "light" : "dark");
    };

    return (
        <div className="flex items-center gap-1 border border-border/40 rounded-none p-1 bg-background/50 backdrop-blur-sm">
            <Button
                variant={size === "small" ? "secondary" : "ghost"}
                size="icon"
                onClick={() => setSize("small")}
                className="h-7 w-7"
                title="Small Text"
            >
                <span className="text-xs font-bold">A</span>
            </Button>
            <Button
                variant={size === "normal" ? "secondary" : "ghost"}
                size="icon"
                onClick={() => setSize("normal")}
                className="h-7 w-7"
                title="Normal Text"
            >
                <span className="text-sm font-bold">A</span>
            </Button>
            <Button
                variant={size === "large" ? "secondary" : "ghost"}
                size="icon"
                onClick={() => setSize("large")}
                className="h-7 w-7"
                title="Large Text"
            >
                <span className="text-lg font-bold">A</span>
            </Button>

            <div className="w-px h-4 bg-border/50 mx-1" />

            <Button
                variant="ghost"
                size="icon"
                onClick={toggleTheme}
                className="h-7 w-7"
                title="Toggle Theme"
            >
                {resolvedTheme === "dark" ? (
                    <Sun className="size-4" />
                ) : (
                    <Moon className="size-4" />
                )}
            </Button>
        </div>
    );
}
