// src/components/Title.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';

    let { title, icon }: { title: string; icon: Snippet } = $props();
</script>

<div class="flex items-center gap-3 mb-6">
    <div class="bg-primary/10 p-2 rounded-none">{@render icon()}</div>
    <h2 class="type-h2">{title}</h2>
</div>

// components/title.tsx
import type React from "react";

const Title = ({ title, icon }: { title: string; icon: React.ReactNode }) => {
	return (
		<div className="flex items-center gap-3 mb-6">
			<div className="bg-primary/10 p-2 rounded-none">{icon}</div>
			<h2 className="type-h2">{title}</h2>
		</div>
	);
};

export default Title;
