// components/tech-badge.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface TechBadgeProps {
	children: React.ReactNode;
	variant?: "default" | "secondary" | "outline" | "destructive";
	className?: string;
}

export function TechBadge({
	children,
	variant = "secondary",
	className,
}: TechBadgeProps) {
	return (
		<Badge
			variant={variant}
			className={cn("rounded-none font-mono text-xs", className)}
		>
			{children}
		</Badge>
	);
}

// src/components/TechBadge.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';
    import { cn } from '@/lib/utils';
    import Badge from '@/components/ui/Badge.svelte';
    import type { BadgeVariant } from '@/lib/ui-variants';

    let {
        variant = 'secondary',
        class: className = '',
        children,
    }: {
        variant?: BadgeVariant;
        class?: string;
        children: Snippet;
    } = $props();
</script>

<Badge {variant} class={cn('rounded-none font-mono text-xs', className)}>
    {@render children()}
</Badge>
