// components/ui/avatar.tsx
"use client";

import * as AvatarPrimitive from "@radix-ui/react-avatar";
import type * as React from "react";

import { cn } from "@/lib/utils";

function Avatar({
	className,
	...props
}: React.ComponentProps<typeof AvatarPrimitive.Root>) {
	return (
		<AvatarPrimitive.Root
			data-slot="avatar"
			className={cn(
				"relative flex size-8 shrink-0 overflow-hidden rounded-none",
				className,
			)}
			{...props}
		/>
	);
}

function AvatarImage({
	className,
	...props
}: React.ComponentProps<typeof AvatarPrimitive.Image>) {
	return (
		<AvatarPrimitive.Image
			data-slot="avatar-image"
			className={cn("aspect-square size-full", className)}
			{...props}
		/>
	);
}

function AvatarFallback({
	className,
	...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
	return (
		<AvatarPrimitive.Fallback
			data-slot="avatar-fallback"
			className={cn(
				"bg-muted flex size-full items-center justify-center rounded-none",
				className,
			)}
			{...props}
		/>
	);
}

export { Avatar, AvatarImage, AvatarFallback };

// src/components/ui/Avatar.svelte
<script lang="ts">
    import { cn } from '@/lib/utils';

    let {
        class: className = '',
        src = '',
        alt = '',
        fallback = '',
        ...rest
    }: {
        class?: string;
        src?: string;
        alt?: string;
        fallback?: string;
    } & Record<string, unknown> = $props();

    let failed = $state(false);
</script>

<div
    class={cn(
        'group/avatar relative flex size-8 shrink-0 overflow-hidden rounded-full select-none',
        className,
    )}
    {...rest}
>
    {#if src && !failed}
        <img
            {src}
            {alt}
            class="aspect-square size-full object-cover"
            onerror={() => (failed = true)}
        />
    {:else}
        <div
            class="bg-muted text-muted-foreground flex size-full items-center justify-center rounded-full text-sm"
        >
            {fallback}
        </div>
    {/if}
</div>
